### ISSUE TITLE
"--help" is not implemented for the "leaderboards" subcommand

### ISSUE THREAD

**Issue by lajp** [Testaustime/testaustime-cli#2]

**Comment by romeq** [comment]
yes, this is true and is being fixed as we speak

**Comment by romeq** [comment]
By the way, what do you exactly mean by the "--help"-flag? No such flag is declared in the code, therefore it's not implemented for "leaderboards" command nor any other subcommand.

Did you mean the `help` command?

**Comment by lajp** [comment]
So does this mean that whever I've been typing `command subcommand --help` it has printed me the usage guide because there is no such command?

**Comment by romeq** [comment]
Yes exactly lol

**Comment by lajp** [comment]
ok xd

**Comment by romeq** [comment]
Also, the synopsis for testaustime is `<testaustime_command> [flags] <command> [subcommand]`; therefore, you shouldn't add any flags after the command.
